In [106]:
!pwd

/home/micha/0_Dev/HACKATHON/AI_Cybersecurity_IDS_PoC/analysis/NN


In [107]:
# load the sonar dataset
from pandas import read_csv
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from autokeras import StructuredDataClassifier

# load dataset
#url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/sonar.csv'
dataframe = pd.read_pickle("../data/unsw-small.pickle")

In [108]:
df_david = pd.read_pickle("../data/davidsSet.pickle")

In [109]:
df_david

duration  orig_pkts  orig_ip_bytes  resp_pkts  resp_ip_bytes
0       175548.663295          1             84      17556         702240
1        22339.587606      54456        4956833          0              0
2        22338.790624      10091         607556          1             52
3          457.696056          0              0        187          12244
4          370.978738        219          17119          1             40
...               ...        ...            ...        ...            ...
475587       0.144119          7           1458          0              0
475588       0.179070          2             80          1             40
475589       0.089327          2             80          1             40
475590       0.359962          9           2192          0              0
475591       0.000000          0              0          0              0

[475592 rows x 5 columns]

In [110]:
df_david['duration'] = [0.0 if isinstance(x,str) else x for x in df_david['duration']]

In [111]:
df_david

duration  orig_pkts  orig_ip_bytes  resp_pkts  resp_ip_bytes
0       175548.663295          1             84      17556         702240
1        22339.587606      54456        4956833          0              0
2        22338.790624      10091         607556          1             52
3          457.696056          0              0        187          12244
4          370.978738        219          17119          1             40
...               ...        ...            ...        ...            ...
475587       0.144119          7           1458          0              0
475588       0.179070          2             80          1             40
475589       0.089327          2             80          1             40
475590       0.359962          9           2192          0              0
475591       0.000000          0              0          0              0

[475592 rows x 5 columns]

In [112]:
#dataframe = dataframe[['dur','orig_pkts','orig_ip_bytes','resp_pkts','resp_ip_bytes','label']]
#dataframe.rename(columns={"dur": "duration"}, errors="raise", inplace=True)
dataframe

duration  orig_pkts  orig_ip_bytes  resp_pkts  resp_ip_bytes  label
0       0.121478          6            258          4            172      0
1       0.649902         14            734         38          42014      0
2       1.623129          8            364         16          13186      0
3       1.681642         12            628         12            770      0
4       0.449454         10            534          6            268      0
...          ...        ...            ...        ...            ...    ...
257668  0.000005          2            104          0              0      0
257669  1.106101         20          18062          8            354      0
257670  0.000000          1             46          0              0      0
257671  0.000000          1             46          0              0      0
257672  0.000009          2            104          0              0      0

[257673 rows x 6 columns]

In [113]:
#dataframe.to_pickle('unsw-small.pickle')

In [114]:
#del dataframe['Unnamed: 0']
#del dataframe['rate']
#del dataframe['attack_cat']

In [115]:
print(dataframe.shape)
# split into input and output elements
data = dataframe.values
X, y = data[:, :-1], data[:, -1]

print(X.shape, y.shape)


(257673, 6)
(257673, 5) (257673,)


In [116]:
X

array([[1.214780e-01, 6.000000e+00, 2.580000e+02, 4.000000e+00,
        1.720000e+02],
       [6.499020e-01, 1.400000e+01, 7.340000e+02, 3.800000e+01,
        4.201400e+04],
       [1.623129e+00, 8.000000e+00, 3.640000e+02, 1.600000e+01,
        1.318600e+04],
       ...,
       [0.000000e+00, 1.000000e+00, 4.600000e+01, 0.000000e+00,
        0.000000e+00],
       [0.000000e+00, 1.000000e+00, 4.600000e+01, 0.000000e+00,
        0.000000e+00],
       [9.000000e-06, 2.000000e+00, 1.040000e+02, 0.000000e+00,
        0.000000e+00]])

In [117]:
# basic data preparation
X = X.astype('float32')
y = LabelEncoder().fit_transform(y)
# separate into train and test sets

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, stratify=y,random_state=42)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(172640, 5) (85033, 5) (172640,) (85033,)


In [118]:
y

array([0, 0, 0, ..., 0, 0, 0])

In [119]:
# define the search
search = StructuredDataClassifier(max_trials=15)

INFO:tensorflow:Reloading Oracle from existing project ./structured_data_classifier/oracle.json
INFO:tensorflow:Reloading Tuner from ./structured_data_classifier/tuner0.json


In [120]:
# perform the search
search.fit(x=X_train, y=y_train, verbose=1)

INFO:tensorflow:Oracle triggered exit
Epoch 1/31
5395/5395 [==============================] - 3s 539us/step - loss: 0.5813 - accuracy: 0.8410
Epoch 2/31
5395/5395 [==============================] - 3s 541us/step - loss: 0.3217 - accuracy: 0.8656
Epoch 3/31
5395/5395 [==============================] - 3s 542us/step - loss: 0.2629 - accuracy: 0.8745
Epoch 4/31
5395/5395 [==============================] - 3s 560us/step - loss: 0.2503 - accuracy: 0.8801
Epoch 5/31
5395/5395 [==============================] - 3s 547us/step - loss: 0.2403 - accuracy: 0.8860
Epoch 6/31
5395/5395 [==============================] - 3s 569us/step - loss: 0.2327 - accuracy: 0.8887
Epoch 7/31
5395/5395 [==============================] - 3s 566us/step - loss: 0.2277 - accuracy: 0.8909
Epoch 8/31
5395/5395 [==============================] - 3s 564us/step - loss: 0.2228 - accuracy: 0.8934
Epoch 9/31
5395/5395 [==============================] - 3s 544us/step - loss: 0.2197 - accuracy: 0.8945
Epoch 10/31
5395/5395 [===

In [121]:
# evaluate the model
loss, acc = search.evaluate(X_test, y_test, verbose=0)
print('Accuracy: %.3f' % acc)

Accuracy: 0.894


In [122]:
# get the best performing model
model = search.export_model()

In [123]:
# summarize the loaded model
model.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 5)]               0         
_________________________________________________________________
multi_category_encoding (Mul (None, 5)                 0         
_________________________________________________________________
dense (Dense)                (None, 32)                192       
_________________________________________________________________
re_lu (ReLU)                 (None, 32)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 16)                528       
_________________________________________________________________
re_lu_1 (ReLU)               (None, 16)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                

In [124]:
# save the best performing model to file
model.save('model_AI4Sec', overwrite=True, include_optimizer=True)

INFO:tensorflow:Assets written to: model_AI4Sec/assets


In [125]:
import tensorflow as tf
import keras
import numpy as np

In [126]:
loaded = keras.models.load_model("model_AI4Sec")

In [127]:
loaded.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 5)]               0         
_________________________________________________________________
multi_category_encoding (Mul (None, 5)                 0         
_________________________________________________________________
dense (Dense)                (None, 32)                192       
_________________________________________________________________
re_lu (ReLU)                 (None, 32)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 16)                528       
_________________________________________________________________
re_lu_1 (ReLU)               (None, 16)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                

In [128]:
df_david = pd.read_pickle("davidsSet.pickle")
df_david['duration'] = [0.0 if isinstance(x,str) else x for x in df_david['duration']]

In [129]:

data_david = df_david.values
#X, y = data_david[:, :-1], data_david[:, -1]
X = data_david

In [130]:
X[0]

array([1.75548663e+05, 1.00000000e+00, 8.40000000e+01, 1.75560000e+04,
       7.02240000e+05])

In [131]:
from numpy import asarray

In [132]:
X = asarray(X[0]).astype('float32')

In [133]:
yhat = loaded.predict(df_david)
print('Predicted: %.3f' % yhat[0])

Predicted: 1.000


array([[1.],
       [1.],
       [1.],
       ...,
       [0.],
       [1.],
       [1.]], dtype=float32)

In [134]:
new = pd.DataFrame(yhat)

In [135]:
new.describe()

0
count  475592.000000
mean        0.318520
std         0.461969
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         1.000000

In [58]:
for i range(len(yhat)):
    yhat[0]
    

SyntaxError: invalid syntax (<ipython-input-58-3808055f2383>, line 1)